source 'https://rubygems.org'
gem 'chefspec', '3.2.0'
gem 'berkshelf'
group :development do
  gem 'test-kitchen'
  gem 'kitchen-vagrant'
  gem 'guard'
  gem 'guard-kitchen'
  gem 'guard-foodcritic', '>= 1.0'
  gem 'foodcritic', '>= 3.0'
end
